In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

symptom = ['Immunity','Weight loss','Weight Gain','Teeth and bone Strength','Knee pain/arthritis','Blood detoxification','Infection and wounds','Body Pain','Skin disease','Inactiveness','Gastric&Intestine troubles','Hyperthermia or Fever','Diabetes','Cold,cough,throat infections','Vision concerns','Nerve disorder','PCOS','Headache','Respiratory concerns','Kidney & urinary problems','Heart problems','Constipation','Diarrhoea','Liver','Male Reproductive concerns']
herbs = ['Arugampul', 'Ashwagandha', 'Athimathuram', 'Arapu Leaves', 'Ammal Pacharisi', 'Athi Leaves', 'Arasu Leaves', 'Avuri Leaves', 'Arasu Seeds', 'Arasu pattai', 'Athi pattai', 'Amukura', 'Agraharam', 'Ashoka pattai', 'Aada Thodai', 'Aavaram Flowers', 'Aadu Theenda Palai', 'Avarai Panchangam', 'Aalamaram Seeds', 'Aalamaram pattai', 'Orange Peel', 'Aali Seeds', 'Aavarai Leaves', 'Lavangam pattai', 'Indhupu Flowers', 'Impural Flowers', 'Usilai', 'Oridhal Thamarai', 'Lemon Peel', 'Omam', 'Kandangkathiri', 'Kadukaai', 'Kasthuri Manjal', 'Curry Leaves', 'Karunjeeragam', 'Kabasura', 'Karungaali pattai', 'Karuvelam pattai', 'Kandanthipilli', 'Kalarchikaai', 'Kaasini Keerai', 'Kaarboga Arisi', 'Krambu', 'Keelanelli', 'Kuppaimeni', 'Kurunthotti Root', 'Koovai Kilangu', 'Kodi Veli', 'Kottai Karanthai', 'Guava Leaves', 'Korai Kilangu', 'Sadhakuppai', 'Srpagandha root', 'Sarkarai Kolli', 'Siru Thekkku', 'Sirukurinjaan', 'Siru Nerunjil', 'Siriyaanangai', 'Sitharathai', 'Siruthumbai leaves', 'Siruseruppadai', 'Sirupeelai', 'Sirupayaru', 'Sivanaar Vembu', 'Sivakaranthai', 'Seeragam', 'Seenthal kodi', 'Sukku', 'Surathu Nila aavarai', 'Surathu Nilaivaagai', 'Sembaruthi Flowers', 'Sabja seeds', 'Sevviyam', 'Aloe Vera', 'Thaneervittan Kilangu', 'Thaandri Kaai', 'Thaalisapathiri leaves', 'Thippli', 'Thiruneetru Pachilai', 'Thuthi Leaves', 'Tulsi Leaves', 'Thuthi Seeds', 'Thudhuvalai', 'Thottal Sivungi', 'Devatharu', 'Thetran Kottai', 'Nannari', 'Nathai Soori', 'Naaval Seeds', 'Nayuruvi Leaves', 'Naval pattai', 'Naalpamaraathi', 'Nilavembu ', 'Nithya kalyani roots', 'Nithya kalyani leaves', 'Nilavaagai', 'Nilapanai kizhangu', 'Neermulli', 'Neermulli seeds', 'Neeli auri leaves', 'Nochi leaves', 'Nellikai', 'Parpadagam', 'Paal mudhingan', 'Parangi pattai', 'Pakarkai', 'Badham Pisin', 'Pirandai', 'Pudhina leaves', 'Boomi chakkarai kilangu', 'Poovasaram pattai', 'Poolangilangu', 'Poonai kaali vidhai', 'Ponkorandi root', 'Ponnagkanni', 'Manjal karisalaangkanni', 'Mara manjal ', 'Magilam flowers', 'Marutham pattai', 'Marudhani leaves', 'Manathakkali ', 'Maavilangapattai', 'Maathulai peel', 'Maasikkaai', 'Maamparupu', 'Milagu', 'Mudakkathan', 'Musumusukkai leaf', 'Murungai Vidhai', 'Murungai Poo', 'Murungai pisin', 'Murungai leaves', 'Multhani matti', 'Mookaratai saaranai', 'Yaanai nerinjil', 'Roja Idhazh ', 'Vallarai', 'Vasambu', 'Vatta thiruppi', 'Vaazhai thandu', 'Vaaivilangam', 'Vadhanarayanan', 'Vaadhamadakki', 'Vishnugranthi', 'Virali manjal', 'Vilvam leaves', 'Vellai karisalaangkanni', 'Vettiver', 'Vendhayam', 'Venthamarai flowers', 'Vellarugu', 'Vellari seeds', 'Veppam leaves', 'Veppam flowers', 'Veliparuthi', 'Veppam pattai', 'Jadhikkai', 'Tulsi seeds', 'Sembaruthi leaves', 'Shataveri']

lst=[]

for i in range(0,len(symptom)):
    lst.append(0)
lst

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [2]:
df = pd.read_csv("Finaldata.csv")
df.replace({'Herb Name':{'Arugampul': 0, 'Ashwagandha': 1, 'Athimathuram': 2, 'Arapu Leaves': 3, 'Ammal Pacharisi': 4, 'Athi Leaves': 5, 'Arasu Leaves': 6, 'Avuri Leaves': 7, 'Arasu Seeds': 8, 'Arasu pattai': 9, 'Athi pattai': 10, 'Amukura': 11, 'Agraharam': 12, 'Ashoka pattai': 13, 'Aada Thodai': 14, 'Aavaram Flowers': 15, 'Aadu Theenda Palai': 16, 'Avarai Panchangam': 17, 'Aalamaram Seeds': 18, 'Aalamaram pattai': 19, 'Orange Peel': 20, 'Aali Seeds': 21, 'Aavarai Leaves': 22, 'Lavangam pattai': 23, 'Indhupu Flowers': 24, 'Impural Flowers': 25, 'Usilai': 26, 'Oridhal Thamarai': 27, 'Lemon Peel': 28, 'Omam': 29, 'Kandangkathiri': 30, 'Kadukaai': 31, 'Kasthuri Manjal': 32, 'Curry Leaves': 33, 'Karunjeeragam': 34, 'Kabasura': 35, 'Karungaali pattai': 36, 'Karuvelam pattai': 37, 'Kandanthipilli': 38, 'Kalarchikaai': 39, 'Kaasini Keerai': 40, 'Kaarboga Arisi': 41, 'Krambu': 42, 'Keelanelli': 43, 'Kuppaimeni': 44, 'Kurunthotti Root': 45, 'Koovai Kilangu': 46, 'Kodi Veli': 47, 'Kottai Karanthai': 48, 'Guava Leaves': 49, 'Korai Kilangu': 50, 'Sadhakuppai': 51, 'Srpagandha root': 52, 'Sarkarai Kolli': 53, 'Siru Thekkku': 54, 'Sirukurinjaan': 55, 'Siru Nerunjil': 56, 'Siriyaanangai': 57, 'Sitharathai': 58, 'Siruthumbai leaves': 59, 'Siruseruppadai': 60, 'Sirupeelai': 61, 'Sirupayaru': 62, 'Sivanaar Vembu': 63, 'Sivakaranthai': 64, 'Seeragam': 65, 'Seenthal kodi': 66, 'Sukku': 67, 'Surathu Nila aavarai': 68, 'Surathu Nilaivaagai': 69, 'Sembaruthi Flowers': 70, 'Sabja seeds': 71, 'Sevviyam': 72, 'Aloe Vera': 73, 'Thaneervittan Kilangu': 74, 'Thaandri Kaai': 75, 'Thaalisapathiri leaves': 76, 'Thippli': 77, 'Thiruneetru Pachilai': 78, 'Thuthi Leaves': 79, 'Tulsi Leaves': 80, 'Thuthi Seeds': 81, 'Thudhuvalai': 82, 'Thottal Sivungi': 83, 'Devatharu': 84, 'Thetran Kottai': 85, 'Nannari': 86, 'Nathai Soori': 87, 'Naaval Seeds': 88, 'Nayuruvi Leaves': 89, 'Naval pattai': 90, 'Naalpamaraathi': 91, 'Nilavembu ': 92, 'Nithya kalyani roots': 93, 'Nithya kalyani leaves': 94, 'Nilavaagai': 95, 'Nilapanai kizhangu': 96, 'Neermulli': 97, 'Neermulli seeds': 98, 'Neeli auri leaves': 99, 'Nochi leaves': 100, 'Nellikai': 101, 'Parpadagam': 102, 'Paal mudhingan': 103, 'Parangi pattai': 104, 'Pakarkai': 105, 'Badham Pisin': 106, 'Pirandai': 107, 'Pudhina leaves': 108, 'Boomi chakkarai kilangu': 109, 'Poovasaram pattai': 110, 'Poolangilangu': 111, 'Poonai kaali vidhai': 112, 'Ponkorandi root': 113, 'Ponnagkanni': 114, 'Manjal karisalaangkanni': 115, 'Mara manjal ': 116, 'Magilam flowers': 117, 'Marutham pattai': 118, 'Marudhani leaves': 119, 'Manathakkali ': 120, 'Maavilangapattai': 121, 'Maathulai peel': 122, 'Maasikkaai': 123, 'Maamparupu': 124, 'Milagu': 125, 'Mudakkathan': 126, 'Musumusukkai leaf': 127, 'Murungai Vidhai': 128, 'Murungai Poo': 129, 'Murungai pisin': 130, 'Murungai leaves': 131, 'Multhani matti': 132, 'Mookaratai saaranai': 133, 'Yaanai nerinjil': 134, 'Roja Idhazh ': 135, 'Vallarai': 136, 'Vasambu': 137, 'Vatta thiruppi': 138, 'Vaazhai thandu': 139, 'Vaaivilangam': 140, 'Vadhanarayanan': 141, 'Vaadhamadakki': 142, 'Vishnugranthi': 143, 'Virali manjal': 144, 'Vilvam leaves': 145, 'Vellai karisalaangkanni': 146, 'Vettiver': 147, 'Vendhayam': 148, 'Venthamarai flowers': 149, 'Vellarugu': 150, 'Vellari seeds': 151, 'Veppam leaves': 152, 'Veppam flowers': 153, 'Veliparuthi': 154, 'Veppam pattai': 155, 'Jadhikkai': 156, 'Tulsi seeds': 157, 'Sembaruthi leaves': 158, 'Shataveri': 159}},inplace=True) 
df.head()

Herb Name  Immunity  Weight loss  Weight Gain  Teeth and bone Strength  \
0         14         0            0            0                        0   
1         14         0            0            0                        0   
2         14         0            0            0                        0   
3         14         0            0            0                        0   
4         14         0            0            0                        0   

   Knee pain/arthritis  Blood detoxification  Infection and wounds  Body Pain  \
0                    0                     1                     0          0   
1                    0                     1                     0          0   
2                    0                     1                     0          0   
3                    0                     1                     0          0   
4                    0                     1                     0          0   

   Skin disease  ...  Nerve disorder  PCOS  Headache  Respiratory concerns  \
0             0  ...               0     0         0                     1   
1             0  ...               0     0         0                     0   
2             0  ...               0     0         0                     1   
3             0  ...               0     0         0                     1   
4             0  ...               0     0         0                     0   

   Kidney & urinary problems  Heart problems  Constipation  Diarrhoea  Liver  \
0                          0               0             0          0      0   
1                          0               0             0          0      0   
2                          0               0             0          0      0   
3                          0               0             0          0      0   
4                          0               0             0          0      0   

   Male Reproductive concerns  
0                           0  
1                           0  
2                           0  
3                           0  
4                           0  

[5 rows x 26 columns]

In [3]:
X = df[symptom]
y = df[["Herb Name"]]
np.ravel(y)
X.head()

Immunity  Weight loss  Weight Gain  Teeth and bone Strength  \
0         0            0            0                        0   
1         0            0            0                        0   
2         0            0            0                        0   
3         0            0            0                        0   
4         0            0            0                        0   

   Knee pain/arthritis  Blood detoxification  Infection and wounds  Body Pain  \
0                    0                     1                     0          0   
1                    0                     1                     0          0   
2                    0                     1                     0          0   
3                    0                     1                     0          0   
4                    0                     1                     0          0   

   Skin disease  Inactiveness  ...  Nerve disorder  PCOS  Headache  \
0             0             0  ...               0     0         0   
1             0             0  ...               0     0         0   
2             0             0  ...               0     0         0   
3             0             0  ...               0     0         0   
4             0             0  ...               0     0         0   

   Respiratory concerns  Kidney & urinary problems  Heart problems  \
0                     1                          0               0   
1                     0                          0               0   
2                     1                          0               0   
3                     1                          0               0   
4                     0                          0               0   

   Constipation  Diarrhoea  Liver  Male Reproductive concerns  
0             0          0      0                           0  
1             0          0      0                           0  
2             0          0      0                           0  
3             0          0      0                           0  
4             0          0      0                           0  

[5 rows x 25 columns]

In [4]:
# Reading the testing.csv file
tr = pd.read_csv("data.csv")
tr.replace({'Herb Name':{'Arugampul': 0, 'Ashwagandha': 1, 'Athimathuram': 2, 'Arapu Leaves': 3, 'Ammal Pacharisi': 4, 'Athi Leaves': 5, 'Arasu Leaves': 6, 'Avuri Leaves': 7, 'Arasu Seeds': 8, 'Arasu pattai': 9, 'Athi pattai': 10, 'Amukura': 11, 'Agraharam': 12, 'Ashoka pattai': 13, 'Aada Thodai': 14, 'Aavaram Flowers': 15, 'Aadu Theenda Palai': 16, 'Avarai Panchangam': 17, 'Aalamaram Seeds': 18, 'Aalamaram pattai': 19, 'Orange Peel': 20, 'Aali Seeds': 21, 'Aavarai Leaves': 22, 'Lavangam pattai': 23, 'Indhupu Flowers': 24, 'Impural Flowers': 25, 'Usilai': 26, 'Oridhal Thamarai': 27, 'Lemon Peel': 28, 'Omam': 29, 'Kandangkathiri': 30, 'Kadukaai': 31, 'Kasthuri Manjal': 32, 'Curry Leaves': 33, 'Karunjeeragam': 34, 'Kabasura': 35, 'Karungaali pattai': 36, 'Karuvelam pattai': 37, 'Kandanthipilli': 38, 'Kalarchikaai': 39, 'Kaasini Keerai': 40, 'Kaarboga Arisi': 41, 'Krambu': 42, 'Keelanelli': 43, 'Kuppaimeni': 44, 'Kurunthotti Root': 45, 'Koovai Kilangu': 46, 'Kodi Veli': 47, 'Kottai Karanthai': 48, 'Guava Leaves': 49, 'Korai Kilangu': 50, 'Sadhakuppai': 51, 'Srpagandha root': 52, 'Sarkarai Kolli': 53, 'Siru Thekkku': 54, 'Sirukurinjaan': 55, 'Siru Nerunjil': 56, 'Siriyaanangai': 57, 'Sitharathai': 58, 'Siruthumbai leaves': 59, 'Siruseruppadai': 60, 'Sirupeelai': 61, 'Sirupayaru': 62, 'Sivanaar Vembu': 63, 'Sivakaranthai': 64, 'Seeragam': 65, 'Seenthal kodi': 66, 'Sukku': 67, 'Surathu Nila aavarai': 68, 'Surathu Nilaivaagai': 69, 'Sembaruthi Flowers': 70, 'Sabja seeds': 71, 'Sevviyam': 72, 'Aloe Vera': 73, 'Thaneervittan Kilangu': 74, 'Thaandri Kaai': 75, 'Thaalisapathiri leaves': 76, 'Thippli': 77, 'Thiruneetru Pachilai': 78, 'Thuthi Leaves': 79, 'Tulsi Leaves': 80, 'Thuthi Seeds': 81, 'Thudhuvalai': 82, 'Thottal Sivungi': 83, 'Devatharu': 84, 'Thetran Kottai': 85, 'Nannari': 86, 'Nathai Soori': 87, 'Naaval Seeds': 88, 'Nayuruvi Leaves': 89, 'Naval pattai': 90, 'Naalpamaraathi': 91, 'Nilavembu ': 92, 'Nithya kalyani roots': 93, 'Nithya kalyani leaves': 94, 'Nilavaagai': 95, 'Nilapanai kizhangu': 96, 'Neermulli': 97, 'Neermulli seeds': 98, 'Neeli auri leaves': 99, 'Nochi leaves': 100, 'Nellikai': 101, 'Parpadagam': 102, 'Paal mudhingan': 103, 'Parangi pattai': 104, 'Pakarkai': 105, 'Badham Pisin': 106, 'Pirandai': 107, 'Pudhina leaves': 108, 'Boomi chakkarai kilangu': 109, 'Poovasaram pattai': 110, 'Poolangilangu': 111, 'Poonai kaali vidhai': 112, 'Ponkorandi root': 113, 'Ponnagkanni': 114, 'Manjal karisalaangkanni': 115, 'Mara manjal ': 116, 'Magilam flowers': 117, 'Marutham pattai': 118, 'Marudhani leaves': 119, 'Manathakkali ': 120, 'Maavilangapattai': 121, 'Maathulai peel': 122, 'Maasikkaai': 123, 'Maamparupu': 124, 'Milagu': 125, 'Mudakkathan': 126, 'Musumusukkai leaf': 127, 'Murungai Vidhai': 128, 'Murungai Poo': 129, 'Murungai pisin': 130, 'Murungai leaves': 131, 'Multhani matti': 132, 'Mookaratai saaranai': 133, 'Yaanai nerinjil': 134, 'Roja Idhazh ': 135, 'Vallarai': 136, 'Vasambu': 137, 'Vatta thiruppi': 138, 'Vaazhai thandu': 139, 'Vaaivilangam': 140, 'Vadhanarayanan': 141, 'Vaadhamadakki': 142, 'Vishnugranthi': 143, 'Virali manjal': 144, 'Vilvam leaves': 145, 'Vellai karisalaangkanni': 146, 'Vettiver': 147, 'Vendhayam': 148, 'Venthamarai flowers': 149, 'Vellarugu': 150, 'Vellari seeds': 151, 'Veppam leaves': 152, 'Veppam flowers': 153, 'Veliparuthi': 154, 'Veppam pattai': 155, 'Jadhikkai': 156, 'Tulsi seeds': 157, 'Sembaruthi leaves': 158, 'Shataveri': 159}},inplace=True) 
tr.head()

Herb Name  Immunity  Weight loss  Weight Gain  Teeth and bone Strength  \
0          0         1            0            0                        0   
1          1         1            0            1                        0   
2          2         0            0            0                        0   
3          3         0            0            0                        0   
4          4         0            0            0                        0   

   Knee pain/arthritis  Blood detoxification  Infection and wounds  Body Pain  \
0                    0                     1                     1          0   
1                    0                     0                     0          0   
2                    0                     0                     1          0   
3                    0                     0                     0          0   
4                    0                     0                     0          0   

   Skin disease  ...  Nerve disorder  PCOS  Headache  Respiratory concerns  \
0             0  ...               0     0         0                     0   
1             0  ...               1     0         0                     0   
2             0  ...               0     0         0                     1   
3             1  ...               0     0         0                     0   
4             1  ...               0     0         0                     0   

   Kidney & urinary problems  Heart problems  Constipation  Diarrhoea  Liver  \
0                          0               0             0          0      0   
1                          0               0             0          0      0   
2                          0               0             0          0      0   
3                          0               0             0          0      0   
4                          0               0             1          0      0   

   Male Reproductive concerns  
0                           0  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 26 columns]

In [5]:
X_test = tr[symptom]
y_test = tr[["Herb Name"]]
np.ravel(y_test)
X_test.head()

Immunity  Weight loss  Weight Gain  Teeth and bone Strength  \
0         1            0            0                        0   
1         1            0            1                        0   
2         0            0            0                        0   
3         0            0            0                        0   
4         0            0            0                        0   

   Knee pain/arthritis  Blood detoxification  Infection and wounds  Body Pain  \
0                    0                     1                     1          0   
1                    0                     0                     0          0   
2                    0                     0                     1          0   
3                    0                     0                     0          0   
4                    0                     0                     0          0   

   Skin disease  Inactiveness  ...  Nerve disorder  PCOS  Headache  \
0             0             0  ...               0     0         0   
1             0             0  ...               1     0         0   
2             0             0  ...               0     0         0   
3             1             0  ...               0     0         0   
4             1             0  ...               0     0         0   

   Respiratory concerns  Kidney & urinary problems  Heart problems  \
0                     0                          0               0   
1                     0                          0               0   
2                     1                          0               0   
3                     0                          0               0   
4                     0                          0               0   

   Constipation  Diarrhoea  Liver  Male Reproductive concerns  
0             0          0      0                           0  
1             0          0      0                           1  
2             0          0      0                           0  
3             0          0      0                           0  
4             1          0      0                           0  

[5 rows x 25 columns]

In [6]:
# DECISION TREE MODEL
from sklearn import tree
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

def DecisionTree():
    clf3 = tree.DecisionTreeClassifier()
    clf3 = clf3.fit(X,y)
    y_pred = clf3.predict(X_test)
    print("Decision Tree")
    print("Accuracy: ",accuracy_score(y_test,y_pred))
    print("Normalized Accuracy: ",accuracy_score(y_test,y_pred,normalize=False))
    print("Confusion Matrix")
    conf_matrix = confusion_matrix(y_test,y_pred)
    print(conf_matrix)

DecisionTree()

Decision Tree
Accuracy:  1.0
Normalized Accuracy:  160
Confusion Matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [7]:
user_symptom = ["Inactiveness","Liver","Infection and wounds"]
l2 = []

for i in range(0,len(symptom)):
    l2.append(0)

for j in range(0,len(user_symptom)):
    for k in range(0,len(symptom)):
        if(user_symptom[j] == symptom[k]):
            l2[k] = 1

input_test = [l2]  


clf3 = tree.DecisionTreeClassifier()
clf3 = clf3.fit(X,y)
y_pred = clf3.predict(input_test)
print("Decision Tree")
print(y_pred)

Decision Tree
[7]


C:\Users\dhars\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [11]:
import pickle
pickle_out = open("dtree.pkl","wb")
pickle.dump(clf3,pickle_out)
pickle_out.close()